@startuml
!theme plain
actor Usuario as j
boundary Navegador as br <<View>>
control Flask as fl <<Controller>>
entity Jurado as mj <<class>>
entity tb_jurado as tj <<model>>
database db_svmp as tb

j -> br : clica em registrar
activate br
br -> fl : rota = "/jurado/registrar"
activate fl
fl -> mj ** : instancia(nome:str, instituicao:str)
fl -> mj : registrar_jurado()
activate mj
mj -> tj ** : orm
mj -> tj : registrar_jurado(dados:dict):dict
activate tj
tj -> tb : insert
activate tb
return id_ultimo_inserido
return dict
return dict
return JSON
return "Jurado registrado"
@enduml